#!/usr/bin/env bash
# Transferring file to my server

if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
path="$1"
ip="$2"
user="$3"
ssh_key_path="$4"

# Transfer the file using scp to the user home directory (~)
scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$path" "$user"@"$ip":~
