#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server
# Checking for command line arguments
if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

# Diasbling Strict Host Key checking
scp -o "StrictHostKeyChecking=no" "$path_to_file" -i "$path_to_ssh_key" "$username@$ip:~/"

# Checking if Transfer was successful
if [ $? -eq 0 ]
then
	echo "Transfer Successful"
else
	echo "Transfer not Successful"
fi
