#!/usr/bin/env bash
# Installing Nginx to my web server

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw "Nginx HTTP"

echo "Hello World!" | sudo tee var /var/www/html/index.html

# Configure Nginx to listen on port 80
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 http://new-page-url;
    }

    location = /index.html {
        echo 'Hello World!';
    }

}" | sudo tee /etc/nginx/sites-available/default

# Create a symbolic link to enable the site
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Remove the default Nginx site configuration
sudo rm /etc/nginx/sites-enabled/default

# Testing Nginx configuration
sudo nginx -t

# Reloading the Nginx Services
sudo service nginx reload
