#!/usr/bin/env bash
# Commands to install Nginx on my web-01 server
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

# Testing Nginx configuration
sudo nginx -t

# Reloading the Nginx Services
sudo service nginx reload
