#!/usr/bin/env bash
# Installing Nginx to my web server

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw "Nginx HTTP"

echo "Hello World!" | sudo tee var /var/www/html/index.html

sudo sed -i 's/\blisten 80 default_server\b/listen 80/g' $nginx_conf

# Testing Nginx configuration
sudo nginx -t

# Reloading the Nginx Services
sudo service nginx reload
