#!/usr/bin/env bash
# Configure your Nginx server for redirection

apt-get -y update
apt-get -y install nginx
service nginx start

echo 'Hello World!' | tee /var/www/html/index.html

str_for_redir='server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Josh-dev69 permanent;"

sudo sed -i "s/server_name _;/$str_for_redir/" /etc/nginx/sites-enabled/default

sudo nginx -t

sudo service nginx restart
