#!/usr/bin/env bash
# Configuring server for permanent redirection

# Updating the package and installing Nginx
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw "Nginx HTTP"

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a "moved permanently redirection" (301)
str_for_redir="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Josh-dev69 permanent;"

sudo sed -i "s/server_name _;/$str_for_redir/" /etc/nginx/sites-enabled/default

# Testing configurations syntax errors
sudo nginx -t

# Restart Nginx after implementing changes
sudo service nginx restart
