#!/usr/bin/env bash
# Configuration of load balancer on the server

# Update package list and Install HAProxy
sudo apt -y update
sudo apt install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend web
    bind *:80
    mode http
    default_backend servers

backend servers
    mode http
    balance roundrobin
    server 219004-web-01 18.210.20.16:80 check
    server 219004-web-02 100.26.217.156:80 check
EOL

# Restart HAProxy
sudo service haproxy restart
