#!/usr/bin/env bash
# listening on port 80 of all the server’s active IPv4 IPs 

# Updating the package and installing Nginx
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw "Nginx HTTP"

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a "moved permanently redirection" (301)
str_for_redir="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Josh-dev69 permanent;"

sudo sed -i "s/server_name _;/$str_for_redir/" /etc/nginx/sites-enabled/default

# Creating a 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

str_for_err="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\t\internal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$str_for_err/" /etc/nginx/sites-enabled/default

# Setting up custom HTTP response header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# configures a server to listening on port 80 of all server's active IPv4 IPs
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default

# Testing configurations syntax errors
sudo nginx -t

# Restart Nginx after implementing changes
sudo service nginx restart
