#!/usr/bin/env bash
# A Bash Script that indefinitely writes I am alive! to the file /tmp/my_process,
# In between every I am alive! message, the program should pause for 2 seconds

i=0
while [ $i ]; do
      echo 'I am alive!' >> /tmp/my_process
      sleep 2
done
