#!/usr/bin/env bash
# Installing and configuring ufw on my server

# Updating package and installing ufw if not installed
sudo apt-get update
sudo apt-get install ufw

# Reset UFW to default settings (optional, in case it's already configured)
sudo ufw reset

# Set default policies to block all incoming and allow all outgoing traffic
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow SSH (port 22), HTTP (port 80), and HTTPS (port 443)
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# Enable UFW
sudo ufw enable

# Check the ufw status
sudo ufw status
